const s = [{
	"Quarter": "Final",
	"AwayTimeoutsRemaining": 0,
	"HomeTimeoutsRemaining": 0,
	"GameId": "nba.g.2016122518",
	"SportModern": "nba",
	"YahooIdFull": "nba.g.2016122518",
	"GameUrl": "https://sports.yahoo.com/news/celtics-recover-knicks-rally-win-119-114-194309731--nba.html",
	"LastUpdated": "2016-12-25T11:49:26 +0000",
	"GameStatus": "FINAL",
	"Location": "Madison Square Garden",
	"Venue": "Madison Square Garden",
	"AwayTeamID": "nba.t.2",
	"AwayTeamCSNID": "nba.t.2",
	"AwayTeamYahooIdFull": "nba.t.2",
	"AwayTeam": "Boston",
	"AwayTeamFullName": "Boston Celtics",
	"AwayTeamAbbrev": "BOS",
	"AwayTeamLocation": "Boston",
	"AwayPrimaryColor": "04864c",
	"AwaySecondaryColor": "ffffff",
	"HomeTeamID": "nba.t.18",
	"HomeTeamCSNID": "nba.t.18",
	"HomeTeamYahooIdFull": "nba.t.18",
	"HomeTeam": "New York",
	"HomeTeamFullName": "New York Knicks",
	"HomeTeamAbbrev": "NY",
	"HomeTeamLocation": "New York",
	"HomePrimaryColor": "f48328",
	"HomeSecondaryColor": "ffffff",
	"StartTime": "2016-12-25T17:00:00 +0000",
	"SeasonPhaseId": "season.phase.season",
	"SeasonYear": 2016,
	"AwayScore": 119,
	"HomeScore": 114,
	"PeriodNum": 4,
	"PeriodActive": false,
	"TimeRemainingFrac": 0,
	"Odds": {
		"AwayLine": -110,
		"AwayPoints": -2,
		"HomeLine": -110,
		"HomePoints": 2,
		"OverUnder": 210.5,
		"OverLine": -110,
		"UnderLine": -110,
		"Favorite": "BOS",
		"Line": "-2"
	},
	"TvStations": "ESPN, CSNE, MSG",
	"HomeWins": 16,
	"HomeLosses": 14,
	"HomePlace": "3",
	"HomeDivision": "Atlantic",
	"AwayWins": 18,
	"AwayLosses": 13,
	"AwayPlace": "2",
	"AwayDivision": "Atlantic",
	"WinningTeamId": "nba.t.2",
	"HasHighlights": true
}, {
	"Quarter": "Final",
	"AwayTimeoutsRemaining": 0,
	"HomeTimeoutsRemaining": 0,
	"GameId": "nba.g.2016122505",
	"SportModern": "nba",
	"YahooIdFull": "nba.g.2016122505",
	"GameUrl": "https://sports.yahoo.com/news/lebron-irving-rally-cavaliers-past-warriors-109-108-222912041--nba.html",
	"LastUpdated": "2016-12-25T14:30:38 +0000",
	"GameStatus": "FINAL",
	"Location": "Quicken Loans Arena",
	"Venue": "Quicken Loans Arena",
	"AwayTeamID": "nba.t.9",
	"AwayTeamCSNID": "nba.t.9",
	"AwayTeamYahooIdFull": "nba.t.9",
	"AwayTeam": "Golden State",
	"AwayTeamFullName": "Golden State Warriors",
	"AwayTeamAbbrev": "GS",
	"AwayTeamLocation": "Golden State",
	"AwayPrimaryColor": "042a5c",
	"AwaySecondaryColor": "fedba2",
	"HomeTeamID": "nba.t.5",
	"HomeTeamCSNID": "nba.t.5",
	"HomeTeamYahooIdFull": "nba.t.5",
	"HomeTeam": "Cleveland",
	"HomeTeamFullName": "Cleveland Cavaliers",
	"HomeTeamAbbrev": "CLE",
	"HomeTeamLocation": "Cleveland",
	"HomePrimaryColor": "860038",
	"HomeSecondaryColor": "d6b377",
	"StartTime": "2016-12-25T19:30:00 +0000",
	"SeasonPhaseId": "season.phase.season",
	"SeasonYear": 2016,
	"AwayScore": 108,
	"HomeScore": 109,
	"PeriodNum": 4,
	"PeriodActive": false,
	"TimeRemainingFrac": 0,
	"Odds": {
		"AwayLine": -110,
		"AwayPoints": -3.5,
		"HomeLine": -110,
		"HomePoints": 3.5,
		"OverUnder": 219,
		"OverLine": -110,
		"UnderLine": -110,
		"Favorite": "GS",
		"Line": "-3.5"
	},
	"TvStations": "ABC, C+ D",
	"HomeWins": 23,
	"HomeLosses": 6,
	"HomePlace": "1",
	"HomeDivision": "Central",
	"AwayWins": 27,
	"AwayLosses": 5,
	"AwayPlace": "1",
	"AwayDivision": "Pacific",
	"WinningTeamId": "nba.t.5"
}, {
	"Quarter": "3rd",
	"AwayTimeoutsRemaining": 4,
	"HomeTimeoutsRemaining": 4,
	"GameId": "nba.g.2016122524",
	"SportModern": "nba",
	"YahooIdFull": "nba.g.2016122524",
	"GameUrl": "https://sports.yahoo.com/nba/chicago-bulls-san-antonio-spurs-2016122524/",
	"LastUpdated": "2016-12-24T14:38:24 +0000",
	"GameStatus": "STARTED",
	"Location": "AT&T Center",
	"Venue": "AT&T Center",
	"AwayTeamID": "nba.t.4",
	"AwayTeamCSNID": "nba.t.4",
	"AwayTeamYahooIdFull": "nba.t.4",
	"AwayTeam": "Chicago",
	"AwayTeamFullName": "Chicago Bulls",
	"AwayTeamAbbrev": "CHI",
	"AwayTeamLocation": "Chicago",
	"AwayPrimaryColor": "cc0e3c",
	"AwaySecondaryColor": "000000",
	"HomeTeamID": "nba.t.24",
	"HomeTeamCSNID": "nba.t.24",
	"HomeTeamYahooIdFull": "nba.t.24",
	"HomeTeam": "San Antonio",
	"HomeTeamFullName": "San Antonio Spurs",
	"HomeTeamAbbrev": "SA",
	"HomeTeamLocation": "San Antonio",
	"HomePrimaryColor": "868e95",
	"HomeSecondaryColor": "ffffff",
	"StartTime": "2016-12-25T22:00:00 +0000",
	"SeasonPhaseId": "season.phase.season",
	"SeasonYear": 2016,
	"AwayScore": 71,
	"HomeScore": 71,
	"PeriodNum": 3,
	"PeriodActive": true,
	"TimeRemainingFrac": 208,
	"Odds": {
		"AwayLine": -110,
		"AwayPoints": 8.5,
		"HomeLine": -110,
		"HomePoints": -8.5,
		"OverUnder": 199,
		"OverLine": -115,
		"UnderLine": -105,
		"Favorite": "SA",
		"Line": "-8.5"
	},
	"TvStations": "ABC, C+ D",
	"HomeWins": 24,
	"HomeLosses": 6,
	"HomePlace": "1",
	"HomeDivision": "Southwest",
	"AwayWins": 14,
	"AwayLosses": 15,
	"AwayPlace": "4",
	"AwayDivision": "Central"
}, {
	"GameId": "nba.g.2016122525",
	"SportModern": "nba",
	"YahooIdFull": "nba.g.2016122525",
	"GameUrl": "https://sports.yahoo.com/news/westbrook-thunder-host-timberwolves-christmas-223853042--nba.html",
	"LastUpdated": "2016-12-24T14:40:23 +0000",
	"GameStatus": "SCHEDULED",
	"Location": "Chesapeake Energy Arena",
	"Venue": "Chesapeake Energy Arena",
	"AwayTeamID": "nba.t.16",
	"AwayTeamCSNID": "nba.t.16",
	"AwayTeamYahooIdFull": "nba.t.16",
	"AwayTeam": "Minnesota",
	"AwayTeamFullName": "Minnesota Timberwolves",
	"AwayTeamAbbrev": "MIN",
	"AwayTeamLocation": "Minnesota",
	"AwayPrimaryColor": "045284",
	"AwaySecondaryColor": "ffffff",
	"HomeTeamID": "nba.t.25",
	"HomeTeamCSNID": "nba.t.25",
	"HomeTeamYahooIdFull": "nba.t.25",
	"HomeTeam": "Oklahoma City",
	"HomeTeamFullName": "Oklahoma City Thunder",
	"HomeTeamAbbrev": "OKC",
	"HomeTeamLocation": "Oklahoma City",
	"HomePrimaryColor": "007dc3",
	"HomeSecondaryColor": "ffffff",
	"StartTime": "2016-12-26T01:00:00 +0000",
	"SeasonPhaseId": "season.phase.season",
	"SeasonYear": 2016,
	"AwayScore": 0,
	"HomeScore": 0,
	"Odds": {
		"AwayLine": -112,
		"AwayPoints": 4,
		"HomeLine": -108,
		"HomePoints": -4,
		"OverUnder": 212,
		"OverLine": -110,
		"UnderLine": -110,
		"Favorite": "OKC",
		"Line": "-4"
	},
	"TvStations": "ESPN, FSOK",
	"HomeWins": 18,
	"HomeLosses": 12,
	"HomePlace": "1",
	"HomeDivision": "Northwest",
	"AwayWins": 9,
	"AwayLosses": 20,
	"AwayPlace": "5",
	"AwayDivision": "Northwest"
}, {
	"GameId": "nba.g.2016122513",
	"SportModern": "nba",
	"YahooIdFull": "nba.g.2016122513",
	"GameUrl": "https://sports.yahoo.com/news/clippers-lakers-battle-l-supremacy-christmas-014054816--nba.html",
	"LastUpdated": "2016-12-24T17:42:20 +0000",
	"GameStatus": "SCHEDULED",
	"Location": "Staples Center",
	"Venue": "Staples Center",
	"AwayTeamID": "nba.t.12",
	"AwayTeamCSNID": "nba.t.12",
	"AwayTeamYahooIdFull": "nba.t.12",
	"AwayTeam": "LA Clippers",
	"AwayTeamFullName": "Los Angeles Clippers",
	"AwayTeamAbbrev": "LAC",
	"AwayTeamLocation": "LA Clippers",
	"AwayPrimaryColor": "ec164c",
	"AwaySecondaryColor": "ffffff",
	"HomeTeamID": "nba.t.13",
	"HomeTeamCSNID": "nba.t.13",
	"HomeTeamYahooIdFull": "nba.t.13",
	"HomeTeam": "LA Lakers",
	"HomeTeamFullName": "Los Angeles Lakers",
	"HomeTeamAbbrev": "LAL",
	"HomeTeamLocation": "LA Lakers",
	"HomePrimaryColor": "542684",
	"HomeSecondaryColor": "fdb827",
	"StartTime": "2016-12-26T03:30:00 +0000",
	"SeasonPhaseId": "season.phase.season",
	"SeasonYear": 2016,
	"AwayScore": 0,
	"HomeScore": 0,
	"Odds": {
		"AwayLine": -110,
		"AwayPoints": -7,
		"HomeLine": -110,
		"HomePoints": 7,
		"OverUnder": 212.5,
		"OverLine": -110,
		"UnderLine": -110,
		"Favorite": "LAC",
		"Line": "-7"
	},
	"TvStations": "ESPN, TWSN, PRIME",
	"HomeWins": 11,
	"HomeLosses": 22,
	"HomePlace": "4",
	"HomeDivision": "Pacific",
	"AwayWins": 22,
	"AwayLosses": 9,
	"AwayPlace": "2",
	"AwayDivision": "Pacific"
}];


export default s;
